[versions]
agp = "8.12.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "35"
junit = "4.13.2"
kotlin = "2.2.10"
okio = "3.16.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }

